# Generated by Django 3.2.9 on 2022-04-04 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Husband_Name', models.CharField(max_length=100)),
                ('Wife_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Childrens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Child_Name', models.CharField(max_length=100)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.parents')),
            ],
        ),
    ]
